ANDROID: Incremental fs: Fix 32-bit build
This commit fixes the error:

fs/incfs/pseudo_files.c:1165:17: error: incompatible types when assigning to
type ‘struct timespec’ from type ‘struct timespec64’

Fixes: 664b74271565 ("ANDROID: Incremental fs: Separate pseudo-file code")
Signed-off-by: Paul Lawrence <paullawrence@google.com>
Change-Id: I0cf24954787c42d475a66ffe0646c47a307bcc26